import Home from "./Home";
import About from "./About";
import Login from "./Login";
import Signup from "./Signup";
import MyCourses from "./MyCourses";
import Profile from "./Profile";
import CourseDetail from "./CourseDetail";
import Payment from "./Payment";
import Thankyou from "./ThankYou";
import MyCOurseVideos from "./MyCOurseVideos";
export { Home, Signup, Login, MyCourses, About, Profile, CourseDetail, Payment, Thankyou, MyCOurseVideos };